### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by Gael-de-Sailly** [rzzzwilson/pySlip#54]
I downloaded and installed latest PySlip and tried to run the demo file.
I got this screen:
![capture du 2017-04-20 14 17 57](https://cloud.githubusercontent.com/assets/6905002/25230492/6fd8f7b4-25d4-11e7-9ce5-e775d834b537.png)
I'm on Ubuntu 14.04.

[pyslip_demo.py line 332](https://github.com/rzzzwilson/pySlip/blob/f909828/pyslip/examples/pyslip_demo.py#L332)
[gmt_local_tiles.py line 97](https://github.com/rzzzwilson/pySlip/blob/f909828/pyslip/gmt_local_tiles.py#L97)

**Comment by RedFiveAZ** [comment]
Same exact issue here on Win10. Any help??

**Comment by DomagojHack** [comment]
Same exact issue! ubuntu 17.10!

**Comment by rzzzwilson** [comment]
Closing this since now moving to python 3 and wxPython 4.  That will take a while, but it is sort of working now.

Sorry, about all the comments I ignored, but I had planned to abandon pySlip due to a perceived lack of users, but I see that we have at least a couple of people looking at it.
